"""Document overview data structures."""

from dataclasses import dataclass
from enum import StrEnum


class OverviewStatus(StrEnum):
    """Status of document overview generation."""

    PENDING = "pending"
    READY = "ready"
    FAILED = "failed"


@dataclass(frozen=True)
class OverviewSection:
    """A section of the document description."""

    heading: str
    body: str


@dataclass(frozen=True)
class DocumentOverview:
    """Complete document overview generated by LLM."""

    summary: str
    language: str
    doc_type: str
    topics: list[str]
    sections: list[OverviewSection]
